In [ ]:
pip install fundamentus

Collecting fundamentus
  Downloading fundamentus-0.3.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: requests>=2.32.4 in /usr/local/lib/python3.12/dist-packages (from fundamentus) (2.32.4)
Collecting requests-cache>=1.2.1 (from fundamentus)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Collecting pandas>=2.3.0 (from fundamentus)
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: lxml>=5.4.0 in /usr/local/lib/python3.12/dist-packages (from fundamentus) (6.1.1)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from fundamentus) (0.9.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.0->fundamentus) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.0->fundamentus) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.4->fundamentus) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.4->fundamentus) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.4->fundamentus) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.4->fundamentus) (2026.6.17)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.2.1->fundamentus) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.2.1->fundamentus)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.2.1->fundamentus) (4.10.0)
Collecting url-normalize>=2.0 (from requests-cache>=1.2.1->fundamentus)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache>=1.2.1->fundamentus) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.3.0->fundamentus) (1.17.0)
Downloading fundamentus-0.3.2-py3-none-any.whl (13 kB)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 74.0 MB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 5.9 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.0 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, pandas, fundamentus
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
Successfully installed cattrs-26.1.0 fundamentus-0.3.2 pandas-3.0.5 requests-cache-1.3.3 url-normalize-3.0.0

In [ ]:
import fundamentus
import pandas as pd

In [ ]:
weg = fundamentus.get_papel("WEGE3")
weg

,Papel,Tipo,Empresa,Setor,Subsetor,Cotacao,Data_ult_cot,Min_52_sem,Max_52_sem,Vol_med_2m,...,Ativo_Circulante,Div_Bruta,Div_Liquida,Patrim_Liq,Receita_Liquida_12m,EBIT_12m,Lucro_Liquido_12m,Receita_Liquida_3m,EBIT_3m,Lucro_Liquido_3m
WEGE3,WEGE3,ON N1,WEG SA ON N1,Máquinas e Equipamentos,"Motores, Compressores e Outros",48.80,2026-08-05,34.16,53.83,359975000,...,30055100000,5066350000,-3734800000,18861400000,40130200000,8400030000,6254050000,10143600000,2107770000,1558630000

In [ ]:
carteira_fund = ["ABEV3", "B3SA3", "AXIA3", "GGBR4", "ITSA4", "PETR4", "RENT3", "SUZB3", "VALE3", "WEGE3"]

In [ ]:
ind = fundamentus.get_papel(carteira_fund)[['Setor', 'Cotacao', 'Min_52_sem', 'Max_52_sem', 'Valor_de_mercado', 'Nro_Acoes', 'Patrim_Liq','Receita_Liquida_12m','Receita_Liquida_3m', 'Lucro_Liquido_12m', 'Lucro_Liquido_3m']]
ind = ind.reset_index()
ind.rename(columns={"index":"Ativo"}, inplace=True)
ind

,Ativo,Setor,Cotacao,Min_52_sem,Max_52_sem,Valor_de_mercado,Nro_Acoes,Patrim_Liq,Receita_Liquida_12m,Receita_Liquida_3m,Lucro_Liquido_12m,Lucro_Liquido_3m
0,ABEV3,Bebidas,15.84,11.11,16.91,249696000000,15763700000,88313200000,88268300000,20148900000,16246900000,3386910000
1,AXIA3,Energia Elétrica,53.71,28.81,67.15,158080000000,2943220000,121148000000,43579000000,12711600000,9541180000,2629670000
2,B3SA3,Serviços Financeiros Diversos,15.55,11.72,19.60,78473100000,5046500000,18255700000,11666100000,3201740000,4956510000,1476970000
3,GGBR4,Siderurgia e Metalurgia,26.31,15.44,26.31,52041700000,1978020000,53544600000,69543700000,17870600000,2237080000,1453790000
4,ITSA4,Intermediários Financeiros,13.73,9.47,14.84,153964000000,11213700000,90196000000,8365000000,2019000000,16983000000,4410000000
5,PETR4,"Petróleo, Gás e Biocombustíveis",41.93,27.94,48.67,540425000000,12888700000,445189000000,498091000000,123686000000,107583000000,32663000000
6,RENT3,Diversos,39.20,30.23,51.79,44070900000,1124260000,26309600000,43926700000,12284400000,2254120000,1221900000
7,SUZB3,Madeira e Papel,42.84,39.68,58.98,54154800000,1264120000,48036000000,49531200000,10968400000,11372800000,4305400000
8,VALE3,Mineração,76.66,49.79,90.09,340306000000,4439160000,196635000000,218069000000,53012000000,10369000000,6847000000
9,WEGE3,Máquinas e Equipamentos,48.80,34.16,53.83,204829000000,4197320000,18861400000,40130200000,10143600000,6254050000,1558630000

In [ ]:
colunas = ['Cotacao', 'Min_52_sem', 'Max_52_sem', 'Valor_de_mercado', 'Nro_Acoes', 'Patrim_Liq',
           'Receita_Liquida_12m', 'Receita_Liquida_3m', 'Lucro_Liquido_12m', 'Lucro_Liquido_3m']
ind[colunas] = ind[colunas].apply(pd.to_numeric, errors='coerce', axis=1)
ind.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ativo                10 non-null     str
 1   Setor                10 non-null     str
 2   Cotacao              10 non-null     float64
 3   Min_52_sem           10 non-null     float64
 4   Max_52_sem           10 non-null     float64
 5   Valor_de_mercado     10 non-null     float64
 6   Nro_Acoes            10 non-null     float64
 7   Patrim_Liq           10 non-null     float64
 8   Receita_Liquida_12m  10 non-null     float64
 9   Receita_Liquida_3m   10 non-null     float64
 10  Lucro_Liquido_12m    10 non-null     float64
 11  Lucro_Liquido_3m     10 non-null     float64
dtypes: float64(10), str(2)
memory usage: 1.3 KB

In [ ]:
ind_2 = fundamentus.get_resultado_raw().reset_index()
ind_2 = ind_2.query("papel in @carteira_fund")
ind_2 = ind_2[['papel', 'P/L', 'Div.Yield', 'P/VP', 'ROE']].reset_index(drop=True)
ind_2.rename(columns={"papel":"Ativo",
                      "Div.Yield":"DY"}, inplace=True)
ind_2

Multiples  Ativo    P/L      DY   P/VP     ROE
0          ABEV3  15.37  0.0570   2.83  0.1840
1          AXIA3  16.57  0.0533   1.30  0.0788
2          B3SA3  15.83  0.0498   4.30  0.2715
3          GGBR4  23.26  0.0262   0.97  0.0418
4          ITSA4   9.07  0.0953   1.71  0.1883
5          PETR4   5.02  0.0708   1.21  0.2417
6          RENT3  19.55  0.0523   1.68  0.0857
7          SUZB3   4.76  0.0001   1.13  0.2368
8          VALE3  32.82  0.0731   1.73  0.0527
9          WEGE3  32.75  0.0411  10.86  0.3316

In [ ]:
indicadores = pd.merge(ind, ind_2, on="Ativo")
indicadores

,Ativo,Setor,Cotacao,Min_52_sem,Max_52_sem,Valor_de_mercado,Nro_Acoes,Patrim_Liq,Receita_Liquida_12m,Receita_Liquida_3m,Lucro_Liquido_12m,Lucro_Liquido_3m,P/L,DY,P/VP,ROE
0,ABEV3,Bebidas,15.84,11.11,16.91,2.496960e+11,1.576370e+10,8.831320e+10,8.826830e+10,2.014890e+10,1.624690e+10,3.386910e+09,15.37,0.0570,2.83,0.1840
1,AXIA3,Energia Elétrica,53.71,28.81,67.15,1.580800e+11,2.943220e+09,1.211480e+11,4.357900e+10,1.271160e+10,9.541180e+09,2.629670e+09,16.57,0.0533,1.30,0.0788
2,B3SA3,Serviços Financeiros Diversos,15.55,11.72,19.60,7.847310e+10,5.046500e+09,1.825570e+10,1.166610e+10,3.201740e+09,4.956510e+09,1.476970e+09,15.83,0.0498,4.30,0.2715
3,GGBR4,Siderurgia e Metalurgia,26.31,15.44,26.31,5.204170e+10,1.978020e+09,5.354460e+10,6.954370e+10,1.787060e+10,2.237080e+09,1.453790e+09,23.26,0.0262,0.97,0.0418
4,ITSA4,Intermediários Financeiros,13.73,9.47,14.84,1.539640e+11,1.121370e+10,9.019600e+10,8.365000e+09,2.019000e+09,1.698300e+10,4.410000e+09,9.07,0.0953,1.71,0.1883
5,PETR4,"Petróleo, Gás e Biocombustíveis",41.93,27.94,48.67,5.404250e+11,1.288870e+10,4.451890e+11,4.980910e+11,1.236860e+11,1.075830e+11,3.266300e+10,5.02,0.0708,1.21,0.2417
6,RENT3,Diversos,39.20,30.23,51.79,4.407090e+10,1.124260e+09,2.630960e+10,4.392670e+10,1.228440e+10,2.254120e+09,1.221900e+09,19.55,0.0523,1.68,0.0857
7,SUZB3,Madeira e Papel,42.84,39.68,58.98,5.415480e+10,1.264120e+09,4.803600e+10,4.953120e+10,1.096840e+10,1.137280e+10,4.305400e+09,4.76,0.0001,1.13,0.2368
8,VALE3,Mineração,76.66,49.79,90.09,3.403060e+11,4.439160e+09,1.966350e+11,2.180690e+11,5.301200e+10,1.036900e+10,6.847000e+09,32.82,0.0731,1.73,0.0527
9,WEGE3,Máquinas e Equipamentos,48.80,34.16,53.83,2.048290e+11,4.197320e+09,1.886140e+10,4.013020e+10,1.014360e+10,6.254050e+09,1.558630e+09,32.75,0.0411,10.86,0.3316

In [ ]:
import yfinance

carteira_yf = ['ABEV3.SA', 'B3SA3.SA', 'GGBR4.SA', 'ITSA4.SA',
               'PETR4.SA', 'RENT3.SA', 'SUZB3.SA', 'VALE3.SA', 'WEGE3.SA']
df = yfinance.download(carteira_yf, start='2026-01-01', end='2026-08-05')
df

/tmp/ipykernel_448/4032826986.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yfinance.download(carteira_yf, start='2026-01-01', end='2026-08-05')
/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[                       0%                       ]/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[***********           22%                       ]  2 of 9 completed/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[****************      33%                       ]  3 of 9 completed/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[**********************56%**                     ]  5 of 9 completed/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[**********************67%*******                ]  6 of 9 completed/usr/local/lib/python3.12/dist-packages/yfinance/scrapers/history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  9 of 9 completed

Price           Close                                                         \
Ticker       ABEV3.SA   B3SA3.SA   GGBR4.SA   ITSA4.SA   PETR4.SA   RENT3.SA
Date
2026-01-02  13.612097  13.178906  20.244864  11.366616  29.781813  42.404545
2026-01-05  13.671931  13.689183  20.442276  11.640275  29.287228  42.697395
2026-01-06  13.661959  14.228901  20.777882  11.689143  28.744152  43.263569
2026-01-07  13.661959  14.013014  20.995037  11.503447  28.928410  42.912148
2026-01-08  13.602125  14.111144  20.925943  11.796653  29.287228  42.531448
...               ...        ...        ...        ...        ...        ...
2026-07-28  16.100000  16.000000  25.139999  13.760000  41.209999  38.369999
2026-07-29  15.900000  15.320000  24.790001  13.490000  42.000000  37.439999
2026-07-30  15.960000  15.630000  24.980000  13.800000  42.840000  38.230000
2026-08-03  15.770000  15.620000  25.629999  13.880000  43.049999  38.099998
2026-08-04  15.870000  15.700000  25.870001  13.650000  42.500000  39.090000

Price                                             High  ...       Open  \
Ticker       SUZB3.SA   VALE3.SA   WEGE3.SA   ABEV3.SA  ...   WEGE3.SA
Date                                                    ...
2026-01-02  51.864731  72.379997  48.033566  13.981070  ...  48.292398
2026-01-05  50.424877  73.120003  47.864330  13.721793  ...  48.043519
2026-01-06  50.224899  75.870003  47.953922  13.811543  ...  48.312308
2026-01-07  49.934925  76.320000  47.486031  13.681904  ...  47.784684
2026-01-08  49.564964  75.580002  45.504959  13.761681  ...  47.336706
...               ...        ...        ...        ...  ...        ...
2026-07-28  43.099998  75.690002  46.700001  16.370001  ...  47.049999
2026-07-29  42.299999  75.050003  45.639999  16.230000  ...  46.610001
2026-07-30  42.730000  76.089996  46.820000  15.960000  ...  45.919998
2026-08-03  43.099998  74.639999  48.200001  16.120001  ...  47.900002
2026-08-04  43.020000  76.309998  49.169998  16.010000  ...  48.900002

Price         Volume                                                    \
Ticker      ABEV3.SA  B3SA3.SA  GGBR4.SA  ITSA4.SA  PETR4.SA  RENT3.SA
Date
2026-01-02  24557600  25030000   5849100  18672900  21625200   5341600
2026-01-05  17543300  26006500   6662200  35859800  48211400   7868600
2026-01-06  28548900  31323200   9874300  16458400  38095000   9868600
2026-01-07  28605400  28359300   9547500  19658100  28132900   8703900
2026-01-08  31130800  74915400   7742900  40016300  34125800   6789700
...              ...       ...       ...       ...       ...       ...
2026-07-28  37458000  19864600  11177000  18269400  29946800  10080200
2026-07-29  37839300  51816200   8309800  15366700  31465400   7096500
2026-07-30  70813600  42168300   9151900  15102700  25268900   4682600
2026-08-03  34419100  30632200   7410900  19025700  24400900   4634000
2026-08-04  28395700  38027600  13538000  22821900  27216700   7746700

Price
Ticker      SUZB3.SA  VALE3.SA  WEGE3.SA
Date
2026-01-02   5570600  28418900   4801300
2026-01-05   4947400  24958100   4531300
2026-01-06   5153600  39536600   5168600
2026-01-07   8357300  41501600   4904900
2026-01-08   5838000  31894900   9557100
...              ...       ...       ...
2026-07-28   6706000  12270800  10923600
2026-07-29  11324800  12265200   6456400
2026-07-30   3591100  16732800   7612900
2026-08-03   4829200  23582200   6927700
2026-08-04   3304700  19784000   6265600

[146 rows x 45 columns]

In [ ]:
cotas = df.stack(level=1)
cotas

Price                    Close       High        Low       Open    Volume
Date       Ticker
2026-01-02 ABEV3.SA  13.612097  13.981070  13.522347  13.841459  24557600
           B3SA3.SA  13.178906  13.463484  13.100402  13.335915  25030000
           GGBR4.SA  20.244864  20.353442  20.057319  20.126414   5849100
           ITSA4.SA  11.366616  11.532766  11.366616  11.483899  18672900
           PETR4.SA  29.781813  30.024257  29.442393  30.024257  21625200
...                        ...        ...        ...        ...       ...
2026-08-04 PETR4.SA  42.500000  43.090000  41.770000  43.090000  27216700
           RENT3.SA  39.090000  39.340000  38.709999  39.080002   7746700
           SUZB3.SA  43.020000  43.709999  42.419998  43.529999   3304700
           VALE3.SA  76.309998  76.910004  75.800003  76.110001  19784000
           WEGE3.SA  49.169998  49.169998  48.369999  48.900002   6265600

[1314 rows x 5 columns]

In [ ]:
cotacoes = cotas.reset_index().rename(columns={'Ticker':'Ativo'})
cotacoes = cotacoes[['Date', 'Ativo','Open','Close','Low','High','Volume']]
cotacoes

Price,Date,Ativo,Open,Close,Low,High,Volume
0,2026-01-02,ABEV3.SA,13.841459,13.612097,13.522347,13.981070,24557600
1,2026-01-02,B3SA3.SA,13.335915,13.178906,13.100402,13.463484,25030000
2,2026-01-02,GGBR4.SA,20.126414,20.244864,20.057319,20.353442,5849100
3,2026-01-02,ITSA4.SA,11.483899,11.366616,11.366616,11.532766,18672900
4,2026-01-02,PETR4.SA,30.024257,29.781813,29.442393,30.024257,21625200
...,...,...,...,...,...,...,...
1309,2026-08-04,PETR4.SA,43.090000,42.500000,41.770000,43.090000,27216700
1310,2026-08-04,RENT3.SA,39.080002,39.090000,38.709999,39.340000,7746700
1311,2026-08-04,SUZB3.SA,43.529999,43.020000,42.419998,43.709999,3304700
1312,2026-08-04,VALE3.SA,76.110001,76.309998,75.800003,76.910004,19784000
1313,2026-08-04,WEGE3.SA,48.900002,49.169998,48.369999,49.169998,6265600

In [ ]:
indicadores['LPA'] = (indicadores['Lucro_Liquido_12m'] / indicadores['Nro_Acoes']).round(2)
indicadores['VPA'] = (indicadores['Patrim_Liq'] / indicadores['Nro_Acoes']).round(2)
# indicadores['P/L'] = (indicadores['Cotacao'] / indicadores['LPA']).round(2)
# indicadores['P/VP'] = (indicadores['Cotacao'] / indicadores['VPA']).round(2)
indicadores

,Ativo,Setor,Cotacao,Min_52_sem,Max_52_sem,Valor_de_mercado,Nro_Acoes,Patrim_Liq,Receita_Liquida_12m,Receita_Liquida_3m,Lucro_Liquido_12m,Lucro_Liquido_3m,P/L,DY,P/VP,ROE,LPA,VPA
0,ABEV3,Bebidas,15.84,11.11,16.91,2.496960e+11,1.576370e+10,8.831320e+10,8.826830e+10,2.014890e+10,1.624690e+10,3.386910e+09,15.37,0.0570,2.83,0.1840,1.03,5.60
1,AXIA3,Energia Elétrica,53.71,28.81,67.15,1.580800e+11,2.943220e+09,1.211480e+11,4.357900e+10,1.271160e+10,9.541180e+09,2.629670e+09,16.57,0.0533,1.30,0.0788,3.24,41.16
2,B3SA3,Serviços Financeiros Diversos,15.55,11.72,19.60,7.847310e+10,5.046500e+09,1.825570e+10,1.166610e+10,3.201740e+09,4.956510e+09,1.476970e+09,15.83,0.0498,4.30,0.2715,0.98,3.62
3,GGBR4,Siderurgia e Metalurgia,26.31,15.44,26.31,5.204170e+10,1.978020e+09,5.354460e+10,6.954370e+10,1.787060e+10,2.237080e+09,1.453790e+09,23.26,0.0262,0.97,0.0418,1.13,27.07
4,ITSA4,Intermediários Financeiros,13.73,9.47,14.84,1.539640e+11,1.121370e+10,9.019600e+10,8.365000e+09,2.019000e+09,1.698300e+10,4.410000e+09,9.07,0.0953,1.71,0.1883,1.51,8.04
5,PETR4,"Petróleo, Gás e Biocombustíveis",41.93,27.94,48.67,5.404250e+11,1.288870e+10,4.451890e+11,4.980910e+11,1.236860e+11,1.075830e+11,3.266300e+10,5.02,0.0708,1.21,0.2417,8.35,34.54
6,RENT3,Diversos,39.20,30.23,51.79,4.407090e+10,1.124260e+09,2.630960e+10,4.392670e+10,1.228440e+10,2.254120e+09,1.221900e+09,19.55,0.0523,1.68,0.0857,2.00,23.40
7,SUZB3,Madeira e Papel,42.84,39.68,58.98,5.415480e+10,1.264120e+09,4.803600e+10,4.953120e+10,1.096840e+10,1.137280e+10,4.305400e+09,4.76,0.0001,1.13,0.2368,9.00,38.00
8,VALE3,Mineração,76.66,49.79,90.09,3.403060e+11,4.439160e+09,1.966350e+11,2.180690e+11,5.301200e+10,1.036900e+10,6.847000e+09,32.82,0.0731,1.73,0.0527,2.34,44.30
9,WEGE3,Máquinas e Equipamentos,48.80,34.16,53.83,2.048290e+11,4.197320e+09,1.886140e+10,4.013020e+10,1.014360e+10,6.254050e+09,1.558630e+09,32.75,0.0411,10.86,0.3316,1.49,4.49